[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native", # Gain access to CPU popcnt and ctzl (recommended by chess crate)
    # "-C", "link-arg=-fuse-ld=mold"
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-cpu=native", # Gain access to CPU popcnt and ctzl (recommended by chess crate)
    # "-C", "link-arg=-fuse-ld=mold"
]
